steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  - name: 'node:20.14'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:20.14'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['use', '${_FIREBASE_PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['target:apply', 'hosting', 'expenses-control-app-5b2b7', 'expenses-control-app-5b2b7', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args: ['deploy', '--token', '${_FIREBASE_TOKEN}', '--only', 'hosting:expenses-control-app-5b2b7']
timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY